#:schema https://developers.openai.com/codex/config-schema.json
project_doc_fallback_filenames = ["CLAUDE.md"]
cli_auth_credentials_store = "file"

personality = "pragmatic"
model = "gpt-5.4"

[projects."/Users/codethread/PersonalConfigs"]
trust_level = "trusted"

[projects."/home/codethread/dev"]
trust_level = "trusted"

[projects."/Users/adamhall/dev"]
trust_level = "trusted"

[projects."/Users/adamhall/PersonalConfigs"]
trust_level = "trusted"

[projects."/Users/adamhall/work"]
trust_level = "trusted"

[projects."/Users/adamhall/workfiles"]
trust_level = "trusted"

[projects."/Users/adamhall/dev/projects/ai-tools"]
trust_level = "trusted"

[projects."/home/codethread/PersonalConfigs"]
trust_level = "trusted"

[projects."/Users/adamhall/dev/projects/cc-inspect"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.3-codex-spark" = 4
